apiVersion: v1
kind: ConfigMap
metadata:
  name: config-manager-config
  namespace: kube-amd-gpu
data:
  config.json: |
    {
      "gpu-config-profiles":
      {
          "default":
          {
              "skippedGPUs": {
                  "ids": [],
                  "product_name": ["MI300", "MI250"]
              },
              "profiles": [
                  {
                      "compute-partition": "CPX", 
                      "memory-partition": "NPS1",
                      "numberofdevices": 1
                  }
              ]
          },
          "profile-1":
          { 
              "deviceFilter": {
                  "ids": [0, 1, 2],
                  "product_name": ["MI300", "MI250"]
              },
              "profiles": [
                  {
                      "compute-partition": "CPX",
                      "memory-partition": "NPS1",
                      "numberofdevices": 8
                  }          
              ]
          }
      }
    }

