---
version: 2.0
builds:
  build-device-config-manager:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/device-config-manager && make dcm"]
    owners: ["email:nkomarla@amd.com"]
    artifacts:
        - /device-config-manager/bin/device-config-manager

  build-device-config-manager-docker:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/device-config-manager && make all"]
    owners: ["email:nkomarla@amd.com"]
    artifacts:
        - /device-config-manager/docker/obj/config-manager-latest.tgz

  build-helm-artifact:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/device-config-manager && make helm-build"]
    owners: ["email:nkomarla@amd.com"]
    artifacts:
        - /device-config-manager/helm-charts/device-config-manager-charts-v1.0.0.tgz

targets:
  api-checks:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/pensando/device-config-manager && \
                                    make checks"]
    owners: ["email:nkomarla@amd.com"]
    area:
    sub-area:
    feature:
    build-dependencies:
        - build-device-config-manager
        - build-device-config-manager-docker

image:
  bind_dir: "/device-config-manager"
  work_dir: "/device-config-manager"

jobs:
  asset-build:
    labels: ["CI-Sanity-Build"]
