apiVersion: v2
name: device-config-manager-charts
description: A Helm chart for AMD GPU Device Config Manager

type: application
version: 0.0.1
appVersion: "0.0.1"
maintainers:
- email: nkomarla@amd.com
  name: Nikhil S K