platform: k8s

nodeSelector: {}

image:
  repository: registry.test.pensando.io:5000/device-config-manager
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

# specify configmap name (mandatory)
configMap: "config-manager-config"